config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'home#top'

  resources :users, only: %i[new create]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :terms_of_services, only: %i[index]
  resources :privacies, only: %i[index]
  resources :shop_lists
  resources :edamams, only: %i[index]
  resources :password_resets, only: %i[create edit update new]
  resource :profile, only: %i[show edit update]

  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_comments, only: %i[create destroy], shallow: true
    collection do
      get :favorite_recipes
    end
  end
  resources :favorite_recipes, only: %i[index create destroy]

  resources :wisdom_boards, only: %i[index show new create edit update destroy] do
    resources :wisdom_comments, only: %i[create destroy], shallow: true
    collection do
      get :favorite_wisdoms
    end
  end
  resources :favorite_wisdoms, only: %i[index create destroy]

  resources :contacts, only: %i[new create complete]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :recipe_comments, dependent: :destroy
  has_many :recipe_photos, dependent: :destroy
  has_many :recipe_ratings, dependent: :destroy
  has_many :recipe_type_of_tags, dependent: :destroy
  has_many :recipe_tags, through: :recipe_type_of_tags
  has_many :favorite_recipes, dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  def index
    if params[:title].present? && params[:tag].present?
      @recipes = Recipe.joins(:recipe_tags).where('recipes.title LIKE ? AND recipe_tags.name LIKE ?', "%#{params[:title]}%",
                                                  "%#{params[:tag]}%").order('recipes.created_at DESC').page(params[:page])
    elsif params[:title].present?
      @recipes = Recipe.where('title LIKE ?', "%#{params[:title]}%").order(created_at: :desc).page(params[:page])
    elsif params[:tag].present?
      @recipes = Recipe.joins(:recipe_tags).where('recipe_tags.name LIKE ?',
                                                  "%#{params[:tag]}%").order('recipes.created_at DESC').page(params[:page])
    else
      @recipes = Recipe.includes(:user).page(params[:page]).order(created_at: :desc)
    end
  end

  def show
    @recipe = Recipe.includes(:user, :recipe_comments, :recipe_tags, :ingredients).find(params[:id])
    @comments = @recipe.recipe_comments.includes(:user).order(created_at: :desc)
    @comment = RecipeComment.new
  end

  def new
    @recipe_form = RecipeForm.new({}, current_user)
  end

  def create
    @recipe_form = RecipeForm.new(recipe_params, current_user)

    if @recipe_form.save
      redirect_to recipes_path, success: 'レシピが作成されました'
    else
      flash.now[:danger] = 'レシピを投稿できませんでした'
      render :new
    end
  end

  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy
    redirect_to recipes_path, success: 'レシピが削除されました'
  end

  def favorite_recipes
    @favorite_recipes = current_user.favorite_recipe_recipes.includes(:user).order(created_at: :desc)
  end

  private

  def recipe_params
    params.require(:recipe_form).permit(
      :title, :content, :cooking_time, :tag_name, :photo,
      ingredients_attributes: %i[id ingredient_name unit_unit],
      recipe_mains: %i[id image description]
    )
  end
end

app/views/recipes/_destroy.html.erb
<% if logged_in? %>
    <% if current_user.own?(recipe) %>
        <%= link_to recipe_path(recipe), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } do %>
            <div class="btn btn-outline-success">削除</div>
        <% end %>
    <% end %>
<% end %>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe_form, url: recipes_path(@recipe), class: 'my-form' do |f| %>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %><span class="text-danger">（必須）</span>
    <%= f.text_field :title, class: 'form-control', placeholder: '簡単！麻薬卵の作り方！！' %>
  </div>
  <div class="form-group">
    <%= f.label :content, '本文' %><span class="text-danger">（必須）</span>
    <%= f.text_area :content, class: 'form-control', placeholder: '料理の特徴や想いなどを書きましょう！' %>
  </div>
  <div class="form-group">
    <%= f.label :cooking_time, '調理時間' %><span class="text-danger">（必須）</span>
    <%= f.text_field :cooking_time, class: 'form-control', placeholder: '〇〇分' %>
  </div>

  <div class="form-group">
    <%= f.label :ingredient_name, '食材名' %>
    <%= f.label :unit_unit, '分量・単位' %><span class="text-danger">（必須）</span>
  </div>

  <table>
    <% (1..15).each do |index| %>
      <tr>
        <td>
          <%= f.text_field "ingredients_attributes[#{index - 1}][ingredient_name]", placeholder: '材料名を入力してください' %>
        </td>
        <td>
          <%= f.text_field "ingredients_attributes[#{index - 1}][unit_unit]", placeholder: '400g、大さじ1杯など' %>
        </td>
      </tr>
    <% end %>
  </table>

  <div class="mb-3">
    <%= f.label :tag_name, 'タグ名' %><span class="text-danger">（必須）</span>
    <%= f.text_field :tag_name, placeholder: ',で区切って入力してください', class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :photo, '写真' %>
    <%= f.file_field :photo, class: 'form-control' %>
  </div>

  <% (1..6).each do |index| %>
  <div class="form-group-photo mt-5">
    <%= f.label "image", "料理の写真 #{index}" %>
    <%= f.file_field "recipe_mains[#{index - 1}][image]", class: 'form-control' %>
  </div>
  <div class="form-group-instruction">
    <%= f.label "description", "料理の作り方 #{index}" %>
    <%= f.text_area "recipe_mains[#{index - 1}][description]", class: 'form-control' %>
  </div>
  
  <% end %>

  <%= f.submit '投稿', class: 'btn btn-success' %>
<% end %>

app/views/recipes/_search_form.html.erb
<%= form_with url: recipes_path, method: :get, data: { turbo_frame: "recipes-frame", controller: "form", action: "input->form#submit" } do |f| %>
  <div class="form-field">
    <div class="form-group">
      <%= f.label :title, 'レシピ名' %>
      <%= f.text_field :title, list: "titles", class:'form-control', placeholder: 'レシピ名で検索してください' %>
      <datalist id="titles">
        <% Recipe.limit(10).each do |recipe| %>
          <option value="<%= recipe.title %>">
        <% end %>
      </datalist>
    </div>
    <div class="form-group">
      <%= f.label :tag, 'タグ名' %>
      <%= f.text_field :tag, list: "tags",  class:'form-control', placeholder: 'タグ名で検索してください' %>
      <datalist id="tags">
        <% RecipeTag.limit(10).each do |tag| %>
          <option value="<%= tag.name %>">
        <% end %>
      </datalist>
    </div>
    <div class="form-submit mt-4">
      <%= f.submit :search, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/recipes/_tags.html.erb
<% @recipe.recipe_tags.each do |tag| %>
    <div class="recipe-tag btn btn-success btn-lg">
      <%= tag.name %>
    </div>
  <% end %>

app/views/recipes/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <%= link_to 'レシピ投稿', new_recipe_path, class: 'btn btn-success mt-3' %>
  <div class="search-form">
    <%= render 'search_form' %>
  </div>

  <div class="boarder mt-3">
    <% @recipes.each do |recipe| %>
      <div class="flex-container">
        <% if logged_in? %>
          <% if current_user.recipe_favorite?(recipe) %>
            <%= render 'favorite_recipes/recipe_unfavorite', {recipe: recipe} %>
          <% else %>
            <%= render 'favorite_recipes/recipe_favorite', { recipe: recipe } %>
          <% end %>
        <% end %>
        <h3 class="ml-3"><%= link_to recipe.title, recipe_path(recipe), class: 'header-link' %></h3>
        <%= render 'destroy', recipe: recipe %>
      </div>
      <% recipe.recipe_tags.each do |tag| %>
        <div class="btn btn-success mb-3 mt-3"><%= tag.name %></div>
      <% end %>
      <div class="recipe_information">
        <%= link_to recipe_path(recipe) do %>
          <%= image_tag recipe.photo_url %>
        <% end %>
      </div>
      <div class="bottom-boarder mt-3"></div>
    <% end %>
  </div>
</div> 
<%= paginate @recipes, theme: 'bootstrap-5' %>

app/views/recipes/new.html.erb
<div class="recipe_edit">
<%= render partial: 'form', locals: { recipe_form: @recipe_form } %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="flex-container">
    <% if logged_in? %>
      <% if current_user.recipe_favorite?(@recipe) %>
        <%= render 'favorite_recipes/recipe_unfavorite', {recipe: @recipe} %>
      <% else %>
        <%= render 'favorite_recipes/recipe_favorite', { recipe: @recipe } %>
      <% end %>
    <% end %>
    <h3 class="recipe-title mt-3"><%= "タイトル：#{@recipe.title}" %></h3>
  </div>

  <div class='mt-2'></div>
  <%= render 'destroy', recipe: @recipe %>
  <h4 class='mt-2'>材料</h4>
  <h4 class='mt-2'><%= "調理時間：#{@recipe.cooking_time}分" %></h4>
  
  <% @recipe.ingredients.each do |recipe_ingredient| %>
    <table class="table table-spacing">
      <tbody>
        <tr>
          <td style="width: 300px;"><%= recipe_ingredient.name %></td>
          <td style="width: 300px;"><%= recipe_ingredient.unit.unit %></td>
        </tr>
      </tbody>
    </table>
  <% end %>

  <div class="recipe-main">
    <div class="btn-group" role="group" aria-label="Recipe Tags">
    <% @recipe.recipe_tags.each do |recipe_tag| %>
      <div class="btn-wrapper">
        <div class="btn btn-success mb-3"><%= recipe_tag.name %></div>
      </div>
    <% end %>
  </div>
    <%= image_tag @recipe.photo_url %>
    <div class="break-all mt-2 mb-2">
      <%= @recipe.content %>
    </div>
  </div>

  <div class="recipe-main">
    <% @recipe.recipe_photos.each_with_index do |recipe_photo, index| %>
      <h3><%= "レシピの説明#{index + 1}" %></h3>
        <%= image_tag recipe_photo.image_url %>
        <div class="break-all mt-2 mb-2">
          <%= recipe_photo.description %>
        </div>
    <% end %>
  </div>

  <%= render 'recipe_comments/form', recipe_comment: @comment, recipe: @recipe %>
  <p class="recipe-author"><%= "投稿者: #{@recipe.user.name}さん" %></p>
  <div id="table-recipe-comment">
    <%= render @comments %>
  </div>
</div>
<%= link_to '一覧に戻る', recipes_path, class: 'Outer-Flex-Text mb-3' %>