config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'home#top'

  resources :users, only: %i[new create]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :terms_of_services, only: %i[index]
  resources :privacies, only: %i[index]
  resources :shop_lists
  resources :edamams, only: %i[index]
  resources :password_resets, only: %i[create edit update new]
  resource :profile, only: %i[show edit update]

  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_comments, only: %i[create destroy], shallow: true
    collection do
      get :favorite_recipes
    end
  end
  resources :favorite_recipes, only: %i[index create destroy]

  resources :wisdom_boards, only: %i[index show new create edit update destroy] do
    resources :wisdom_comments, only: %i[create destroy], shallow: true
    collection do
      get :favorite_wisdoms
    end
  end
  resources :favorite_wisdoms, only: %i[index create destroy]

  resources :contacts, only: %i[new create complete]
end

app/models/application_record.rb
# This is the ApplicationRecord class. It serves as the base class for all ActiveRecord models in the application.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :message, presence: true, length: { maximum: 1_000 }
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :user_id, uniqueness: { scope: :recipe_id }
end

app/models/favorite_wisdom.rb
class FavoriteWisdom < ApplicationRecord
  belongs_to :user
  belongs_to :wisdom_board

  validates :user_id, uniqueness: { scope: :wisdom_board_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_one :unit, dependent: :destroy
  has_many :recipe_ingredient, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :recipe_comments, dependent: :destroy
  has_many :recipe_photos, dependent: :destroy
  has_many :recipe_ratings, dependent: :destroy
  has_many :recipe_type_of_tags, dependent: :destroy
  has_many :recipe_tags, through: :recipe_type_of_tags
  has_many :favorite_recipes, dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :body, presence: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_photo.rb
class RecipePhoto < ApplicationRecord
  mount_uploader :image, RecipeImageUploader
  belongs_to :recipe
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  has_many :recipe_type_of_tags, dependent: :destroy
  has_many :recipes, through: :recipe_type_of_tags

  validates :name, uniqueness: true
end

app/models/recipe_type_of_tag.rb
class RecipeTypeOfTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :recipe_tag
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user

  validates :item, presence: true, length: { maximum: 30 }
  validates :notes, length: { maximum: 30 }
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  has_many :shopping_lists, dependent: :destroy

  has_many :recipes, dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
  has_many :favorite_recipe_recipes, through: :favorite_recipes, source: :recipe

  has_many :ingredients, through: :recipe_ingredients
  has_many :recipe_ingredients, dependent: :destroy

  has_many :recipe_comments, dependent: :destroy
  has_many :recipe_rating, dependent: :destroy

  has_many :wisdom_boards, dependent: :destroy
  has_many :favorite_wisdoms, dependent: :destroy
  has_many :favorite_wisdom_wisdoms, through: :favorite_wisdoms, source: :wisdom_board
  has_many :wisdom_comments, dependent: :destroy

  def own?(object)
    id == object&.user_id
  end

  def recipe_favorite(recipe)
    favorite_recipe_recipes << recipe
  end

  def recipe_unfavorite(recipe)
    favorite_recipe_recipes.destroy(recipe)
  end

  def recipe_favorite?(recipe)
    favorite_recipe_recipes.include?(recipe)
  end

  def wisdom_board_favorite(wisdom_board)
    favorite_wisdom_wisdoms << wisdom_board
  end

  def wisdom_board_unfavorite(wisdom_board)
    favorite_wisdom_wisdoms.destroy(wisdom_board)
  end

  def wisdom_board_favorite?(wisdom_board)
    favorite_wisdom_wisdoms.include?(wisdom_board)
  end
end

app/models/wisdom_board.rb
class WisdomBoard < ApplicationRecord
  mount_uploader :photo, WisdomPhotoUploader
  belongs_to :user
  has_many :favorite_wisdoms, dependent: :destroy
  has_many :wisdom_type_of_tags, dependent: :destroy
  has_many :wisdom_tags, through: :wisdom_type_of_tags
  has_many :wisdom_photos, dependent: :destroy
  has_many :wisdom_comments, dependent: :destroy
  has_many :wisdom_ratings, dependent: :destroy
end

app/models/wisdom_comment.rb
class WisdomComment < ApplicationRecord
  belongs_to :user
  belongs_to :wisdom_board

  validates :comment, presence: true
end

app/models/wisdom_photo.rb
class WisdomPhoto < ApplicationRecord
  mount_uploader :image, WisdomImageUploader
end

app/models/wisdom_tag.rb
class WisdomTag < ApplicationRecord
  has_many :wisdom_type_of_tags, dependent: :destroy
  has_many :wisdom_boards, through: :wisdom_type_of_tags
end

app/models/wisdom_type_of_tag.rb
class WisdomTypeOfTag < ApplicationRecord
  belongs_to :wisdom_board
  belongs_to :wisdom_tag
end

app/helpers/application_helper.rb
# This is the ApplicationHelper module. It provides helper methods for the application.
module ApplicationHelper
  # Helper methods here
  def page_title(title = '')
    base_title = 'Qmeals'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/views/shared/_before_login_header.html.erb
<div id="before_header">
    <div class="top_information">
        <div class="left_header">
            <%= link_to root_path do %>
                <span>Qmeals</span>
                    <%= image_tag 'dish.svg' %>
            <% end %>
        </div>
        <div class="right_header">
                <%= link_to 'ユーザー登録', new_user_path, class: 'btn btn-success mt-3 mb-4' %>
                <%= link_to 'ログイン', login_path, class: 'btn btn-success mt-3 mb-4' %>
        </div>
    </div>
    <div class="middle_information">
        <%= link_to shop_lists_path, class: 'header-link text-brown' do %>
            <%= image_tag 'bag.svg' %>
            <span>お買い物リスト</span>
        <% end %>
        <%= link_to recipes_path, class: 'header-link text-brown' do %>
            <%= image_tag 'pod.svg' %>
            <span>レシピ</span>
        <% end %>
        <%= link_to wisdom_boards_path, class: 'header-link text-brown' do %>
            <%= image_tag 'wisdom.svg' %>
            <span>料理の知恵</span>
        <% end %>
        <%= link_to edamams_path, class: 'header-link text-brown' do %>
            <%= image_tag 'edamams.svg' %>
            <span>海外のレシピ</span>
        <% end %>
        <%= link_to login_path, class: 'header-link text-brown' do %>
            <%= image_tag 'star.svg' %><span>お気に入りリスト</span>
        <% end %>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favorites.html.erb
<div class="row justify-content-around mb-4 mt-3">
  <div class="col-6 col-md-4 col-lg-3">
    <%= link_to 'レシピのお気に入り', favorite_recipes_path, class: 'btn btn-success btn-block' %>
  </div>
  <div class="col-6 col-md-4 col-lg-3 ">
    <%= link_to '料理の知恵のお気に入り', favorite_wisdoms_path, class: 'btn btn-success btn-block' %>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.erb
<div class="footer" id="footer">
    <div class='footer-container'>
        <%= link_to '利用規約', terms_of_services_path, class: 'header-link' %>
        <%= link_to 'プライバシーポリシー', privacies_path, class: 'header-link' %>
        <%= link_to 'お問い合わせ', new_contact_path, class: 'header-link'  %>
    </div>
    <div class='copyright'>
        <p>Copyright© Qmeals All Rights Reserved.</p>
    </div>
</div>

app/views/shared/_header.erb
<div class="header">
  <div class="top_information">
    <div class="left_header">
      <%= link_to root_path, class: 'header-link' do %>
        <span>Qmeals</span>
        <%= image_tag 'dish.svg' %>
      <% end %>
    </div>
    <div class="right_header">
      <%= button_to "ログアウト", logout_path, method: :delete, class: "btn btn-success mt-3 mb-4",
            data: { turbo_method: :delete, turbo_confirm: "本当にログアウトしますか？" } %>
      <%= link_to "#{current_user.name}さん", profile_path, class: 'btn btn-success mt-3 mb-4'%>
      <%= link_to profile_path do %>
        <%= image_tag current_user.avatar_url %>
      <% end %>
    </div>
  </div>
  <div class="middle_information">
    <%= link_to shop_lists_path, class: 'header-link' do %>
      <%= image_tag 'bag.svg' %>
      <span>お買い物リスト</span>
    <% end %>
    <%= link_to recipes_path, class: 'header-link' do %>
      <%= image_tag 'pod.svg' %>
      <span>レシピ</span>
    <% end %>
    <%= link_to wisdom_boards_path, class: 'header-link' do %>
      <%= image_tag 'wisdom.svg' %>
      <span>料理の知恵</span>
    <% end %>
    <%= link_to edamams_path, class: 'header-link' do %>
      <%= image_tag 'edamams.svg' %>
      <span>海外のレシピ</span>
    <% end %>
    <%= link_to favorite_recipes_path, class: 'header-link' do %>
      <%= image_tag 'star.svg' %>
      <span>お気に入りリスト</span>
    <% end %>
  </div>
</div>