config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'home#top'

  resources :users, only: %i[new create]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :terms_of_services, only: %i[index]
  resources :privacies, only: %i[index]
  resources :shop_lists
  resources :edamams, only: %i[index]
  resources :password_resets, only: %i[create edit update new]
  resource :profile, only: %i[show edit update]

  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_comments, only: %i[create destroy], shallow: true
    collection do
      get :favorite_recipes
    end
  end
  resources :favorite_recipes, only: %i[index create destroy]

  resources :wisdom_boards, only: %i[index show new create edit update destroy] do
    resources :wisdom_comments, only: %i[create destroy], shallow: true
    collection do
      get :favorite_wisdoms
    end
  end
  resources :favorite_wisdoms, only: %i[index create destroy]

  resources :contacts, only: %i[new create complete]
end

app/models/application_record.rb
# This is the ApplicationRecord class. It serves as the base class for all ActiveRecord models in the application.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :message, presence: true, length: { maximum: 1_000 }
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :user_id, uniqueness: { scope: :recipe_id }
end

app/models/favorite_wisdom.rb
class FavoriteWisdom < ApplicationRecord
  belongs_to :user
  belongs_to :wisdom_board

  validates :user_id, uniqueness: { scope: :wisdom_board_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_one :unit, dependent: :destroy
  has_many :recipe_ingredient, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :recipe_comments, dependent: :destroy
  has_many :recipe_photos, dependent: :destroy
  has_many :recipe_ratings, dependent: :destroy
  has_many :recipe_type_of_tags, dependent: :destroy
  has_many :recipe_tags, through: :recipe_type_of_tags
  has_many :favorite_recipes, dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :body, presence: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_photo.rb
class RecipePhoto < ApplicationRecord
  mount_uploader :image, RecipeImageUploader
  belongs_to :recipe
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  has_many :recipe_type_of_tags, dependent: :destroy
  has_many :recipes, through: :recipe_type_of_tags

  validates :name, uniqueness: true
end

app/models/recipe_type_of_tag.rb
class RecipeTypeOfTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :recipe_tag
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user

  validates :item, presence: true, length: { maximum: 30 }
  validates :notes, length: { maximum: 30 }
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  has_many :shopping_lists, dependent: :destroy

  has_many :recipes, dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
  has_many :favorite_recipe_recipes, through: :favorite_recipes, source: :recipe

  has_many :ingredients, through: :recipe_ingredients
  has_many :recipe_ingredients, dependent: :destroy

  has_many :recipe_comments, dependent: :destroy
  has_many :recipe_rating, dependent: :destroy

  has_many :wisdom_boards, dependent: :destroy
  has_many :favorite_wisdoms, dependent: :destroy
  has_many :favorite_wisdom_wisdoms, through: :favorite_wisdoms, source: :wisdom_board
  has_many :wisdom_comments, dependent: :destroy

  def own?(object)
    id == object&.user_id
  end

  def recipe_favorite(recipe)
    favorite_recipe_recipes << recipe
  end

  def recipe_unfavorite(recipe)
    favorite_recipe_recipes.destroy(recipe)
  end

  def recipe_favorite?(recipe)
    favorite_recipe_recipes.include?(recipe)
  end

  def wisdom_board_favorite(wisdom_board)
    favorite_wisdom_wisdoms << wisdom_board
  end

  def wisdom_board_unfavorite(wisdom_board)
    favorite_wisdom_wisdoms.destroy(wisdom_board)
  end

  def wisdom_board_favorite?(wisdom_board)
    favorite_wisdom_wisdoms.include?(wisdom_board)
  end
end

app/models/wisdom_board.rb
class WisdomBoard < ApplicationRecord
  mount_uploader :photo, WisdomPhotoUploader
  belongs_to :user
  has_many :favorite_wisdoms, dependent: :destroy
  has_many :wisdom_type_of_tags, dependent: :destroy
  has_many :wisdom_tags, through: :wisdom_type_of_tags
  has_many :wisdom_photos, dependent: :destroy
  has_many :wisdom_comments, dependent: :destroy
  has_many :wisdom_ratings, dependent: :destroy
end

app/models/wisdom_comment.rb
class WisdomComment < ApplicationRecord
  belongs_to :user
  belongs_to :wisdom_board

  validates :comment, presence: true
end

app/models/wisdom_photo.rb
class WisdomPhoto < ApplicationRecord
  mount_uploader :image, WisdomImageUploader
end

app/models/wisdom_tag.rb
class WisdomTag < ApplicationRecord
  has_many :wisdom_type_of_tags, dependent: :destroy
  has_many :wisdom_boards, through: :wisdom_type_of_tags
end

app/models/wisdom_type_of_tag.rb
class WisdomTypeOfTag < ApplicationRecord
  belongs_to :wisdom_board
  belongs_to :wisdom_tag
end

app/controllers/favorite_wisdoms_controller.rb
class FavoriteWisdomsController < ApplicationController
  def index
    @favorite_wisdoms = current_user.favorite_wisdoms.includes(:wisdom_board).map(&:wisdom_board)
  end

  def create
    @wisdom_board = WisdomBoard.find(params[:wisdom_board_id])
    current_user.wisdom_board_favorite(@wisdom_board)
  end

  def destroy
    @wisdom_board = current_user.favorite_wisdoms.find(params[:id]).wisdom_board
    current_user.wisdom_board_unfavorite(@wisdom_board)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
end

app/helpers/application_helper.rb
# This is the ApplicationHelper module. It provides helper methods for the application.
module ApplicationHelper
  # Helper methods here
  def page_title(title = '')
    base_title = 'Qmeals'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/views/favorite_wisdoms/_wisdom_favorite.html.erb
<%= link_to favorite_wisdoms_path(wisdom_board_id: wisdom_board.id), id: "favorite-button-for-wisdom-#{wisdom_board.id}", data: { turbo_method: :post } do %>
  <div><%= image_tag 'unfavorite.svg' %></div>
<% end %>

app/views/favorite_wisdoms/_wisdom_unfavorite.html.erb
<%= link_to favorite_wisdom_path(current_user.favorite_wisdoms.find_by(wisdom_board_id: wisdom_board.id)), id: "favorite-button-for-wisdom-#{wisdom_board.id}", data: { turbo_method: :delete } do %>
  <div><%= image_tag 'favorite.svg' %></div>
<% end %>

app/views/favorite_wisdoms/create.turbo_stream.erb
<%= turbo_stream.replace "favorite-button-for-wisdom-#{@wisdom_board.id}" do %>
  <%= render 'favorite_wisdoms/wisdom_unfavorite', wisdom_board: @wisdom_board %>
<% end %>

app/views/favorite_wisdoms/destroy.turbo_stream.erb
<%= turbo_stream.replace "favorite-button-for-wisdom-#{@wisdom_board.id}" do %>
  <%= render 'favorite_wisdoms/wisdom_favorite', wisdom_board: @wisdom_board %>
<% end %>

app/views/favorite_wisdoms/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <%= render 'shared/favorites' %>
  <div class="bottom-boarder"></div>
  <% @favorite_wisdoms.each do |wisdom_board| %>
    <div class="favorite-wisdom-board">
      <div style="display: flex; align-items: center;">
        <%= render 'wisdom_unfavorite', {wisdom_board: wisdom_board} %>
        <h3 class="ml-3"><%= link_to wisdom_board.title, wisdom_board_path(wisdom_board), class: 'header-link' %></h3>
      </div>
      <% wisdom_board.wisdom_tags.each do |tag| %>
        <span class="btn btn-success"><%= tag.name %></span>
      <% end %>
      <p class="mt-3">
        <%= link_to wisdom_board_path(wisdom_board) do %>
          <div class="image-box"><%= image_tag wisdom_board.photo_url %></div>
        <% end %>
      </p>
      <div class="bottom-boarder"></div>
    </div>
  <% end %>
  </div>
</div>